##Demo 4 - Image Handling Using NumPy

In this demo, you will learn about image handling using numpy

######Install the necessary package for Image Handling.
######Note: In collab, numpy and Pillow will be installed implicitly.

In [ ]:
!pip install numpy

In [ ]:
!pip install Pillow

In [ ]:
# Import the necessary libraries
import PIL

#Check the version of Pillow installed
print('Installed Pillow Version:', PIL.__version__)

from PIL import Image
from numpy import asarray

Installed Pillow Version: 11.0.0


Open the image file that you need to handling

In [ ]:
image = Image.open('AI.png')

# getting thedetails about the image
print(image.format)
print(image.size)
print(image.mode)

PNG
(670, 448)
RGBA


In [ ]:
# load the image and convert into
# numpy array
img = Image.open('AI.png')

# asarray() class is used to convert
# PIL images into NumPy arrays
numpydata = asarray(img)

# <class 'numpy.ndarray'>
print(type(numpydata))

# shape
print(numpydata.shape)


<class 'numpy.ndarray'>
(448, 670, 4)


In [ ]:
from PIL import Image
import numpy


img= Image.open("AI.png")
np_img = numpy.array(img)

print(np_img.shape)

(448, 670, 4)


In [ ]:
# load the image and convert into
# numpy array
img = Image.open('AI.png')
numpydata = asarray(img)

# data
print(numpydata)

[[[ 78  97  38 165]
  [ 79  97  39 255]
  [ 79  97  39 255]
  ...
  [ 79  97  39 255]
  [ 79  97  39 255]
  [ 78  97  38 165]]

 [[ 79  97  39 255]
  [ 79  97  39 255]
  [ 79  97  39 255]
  ...
  [ 79  97  39 255]
  [ 79  97  39 255]
  [ 79  97  39 255]]

 [[ 79  97  39 255]
  [ 79  97  39 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [ 79  97  39 255]
  [ 79  97  39 255]]

 ...

 [[ 79  97  39 255]
  [ 79  97  39 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [ 79  97  39 255]
  [ 79  97  39 255]]

 [[ 79  97  39 255]
  [ 79  97  39 255]
  [ 79  97  39 255]
  ...
  [ 79  97  39 255]
  [ 79  97  39 255]
  [ 79  97  39 255]]

 [[ 78  97  38 165]
  [ 79  97  39 255]
  [ 79  97  39 255]
  ...
  [ 79  97  39 255]
  [ 79  97  39 255]
  [ 78  97  38 165]]]


In [ ]:
# Import the necessary libraries
from PIL import Image
from numpy import asarray


# load the image and convert into
# numpy array
img = Image.open('AI.png')
numpydata = asarray(img)

print(type(numpydata))

# shape
print(numpydata.shape)

# Below is the way of creating Pillow
# image from our numpyarray
pilImage = Image.fromarray(numpydata)
print(type(pilImage))

# Let us check image details
print(pilImage.mode)
print(pilImage.size)


<class 'numpy.ndarray'>
(448, 670, 4)
<class 'PIL.Image.Image'>
RGBA
(670, 448)


#### Conclusion: This code demonstrates how to perform image handling in numpy.